export const methods = [
	{
		id: 1,
		name: 'USDT',
		address: 'TL6SLbsFrK77H3VBK6iBJHSfCfZ4aKgmsd',
		img: 'https://i.ibb.co/xCmrr4n/usdt.png',
		qr: 'https://i.ibb.co/2dtx3df/qrcode1.png',
		title: 'USDT (TRC-20)',
		isActive: true,
	},
	// {
	// 	id: 2,
	// 	name: 'Bitcoin ',
	// 	address: '1QAGVXACQJgZRNgZQrXBSPKkh6RZPrAvwr',
	// 	img: 'https://i.ibb.co/51LzBQT/bit.png',
	// 	qr: 'https://i.ibb.co/2dtx3df/qrcode1.png',
	// 	title: 'Bitcoin',
	// 	isActive: true,
	// },
	// {
	// 	id: 3,
	// 	name: 'BNB',
	// 	address: 'bnb136ns6lfw4zs5hg4n85vdthaad7hq5m4gtkgf23',
	// 	img: 'https://i.ibb.co/h7C4brr/bnb.png',
	// 	qr: 'https://i.ibb.co/2dtx3df/qrcode1.png',
	// 	title: '',
	// 	isActive: false,
	// },
	// {
	// 	id: 4,
	// 	name: 'Ethereum',
	// 	balance: '0.00',
	// 	address: '0x9bf88ae39c3ebcbaf96824d3a774fcf9c248407c',
	// 	img: 'https://i.ibb.co/Jd72Czt/ethereum.png',
	// 	qr: 'https://i.ibb.co/2dtx3df/qrcode1.png',
	// 	title: '',
	// 	isActive: false,
	// },
	// {
	// 	id: 5,
	// 	name: 'Litecoin',
	// 	balance: '0.00',
	// 	address: 'LgfVQJhEJTw4fsDSre6ijJxMoKsBo4b5oP',
	// 	img: 'https://i.ibb.co/rdPrFqc/litacoin.png',
	// 	qr: 'https://i.ibb.co/2dtx3df/qrcode1.png',
	// 	title: 'Litecoin',
	// 	isActive: true,
	// },
];
